/*
 * Welcome
 */
package com.achess.practica1apuestas.UI;

import com.achess.practica1apuestas.betsLogic.Bet;
import com.achess.practica1apuestas.betsLogic.Bets;
import com.achess.practica1apuestas.file.FileManagment;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author achess
 */
public class PanelApuestas extends javax.swing.JPanel {

    /**
     * Creates new form panelApuestas
     */
    public PanelApuestas() {
        initComponents();
        customInit();
    }
    
    private void customInit(){        
        JTextField a = new JTextField();
        textMonto.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){                                
                char c = e.getKeyChar();
                if( (c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE){
                    e.consume();
                }
            }
        });
    }
    
    private void saveFile(){
        Bets bets = Bets.getBets();
        if(FileManagment.selectDirectory() && FileManagment.save(bets.getRejected())){            
                JOptionPane.showMessageDialog(this, "Archivo guardado con éxito");            
        }else{
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo");
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textMonto = new javax.swing.JTextField();
        combo1ro = new javax.swing.JComboBox<>();
        combo2do = new javax.swing.JComboBox<>();
        combo3ro = new javax.swing.JComboBox<>();
        combo4to = new javax.swing.JComboBox<>();
        combo5to = new javax.swing.JComboBox<>();
        combo10mo = new javax.swing.JComboBox<>();
        combo8vo = new javax.swing.JComboBox<>();
        combo9no = new javax.swing.JComboBox<>();
        combo6to = new javax.swing.JComboBox<>();
        combo7mo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        buttonVerify = new javax.swing.JButton();

        setBackground(new java.awt.Color(14, 14, 16));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(675, 437));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nombre apostador:");

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Monto Q");

        combo1ro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo1ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1roActionPerformed(evt);
            }
        });

        combo2do.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo2do.setSelectedIndex(1);
        combo2do.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2doActionPerformed(evt);
            }
        });

        combo3ro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo3ro.setSelectedIndex(2);
        combo3ro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo3roActionPerformed(evt);
            }
        });

        combo4to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo4to.setSelectedIndex(3);
        combo4to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo4toActionPerformed(evt);
            }
        });

        combo5to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo5to.setSelectedIndex(4);
        combo5to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo5toActionPerformed(evt);
            }
        });

        combo10mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo10mo.setSelectedIndex(9);
        combo10mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo10moActionPerformed(evt);
            }
        });

        combo8vo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo8vo.setSelectedIndex(7);
        combo8vo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo8voActionPerformed(evt);
            }
        });

        combo9no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo9no.setSelectedIndex(8);
        combo9no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo9noActionPerformed(evt);
            }
        });

        combo6to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo6to.setSelectedIndex(5);
        combo6to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo6toActionPerformed(evt);
            }
        });

        combo7mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        combo7mo.setSelectedIndex(6);
        combo7mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo7moActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("1ro.");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("2do.");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("3ro.");

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("4to.");

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("5to.");

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("6to.");

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("7mo.");

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("8vo.");

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("9no.");

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("10mo.");

        jButton2.setBackground(new java.awt.Color(151, 123, 252));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Agregar apuesta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(151, 123, 252));
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Cargar archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        buttonVerify.setBackground(new java.awt.Color(250, 66, 59));
        buttonVerify.setForeground(java.awt.Color.white);
        buttonVerify.setText("Verificar/Guardar");
        buttonVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo4to, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo5to, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo6to, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo1ro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo2do, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combo3ro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(combo7mo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo10mo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(9, 9, 9)
                                .addComponent(combo8vo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo9no, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonVerify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textName)
                    .addComponent(jLabel2)
                    .addComponent(textMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo1ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo2do, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo3ro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo6to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(combo4to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(combo5to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo7mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(combo8vo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(combo9no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo10mo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combo1roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1roActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1roActionPerformed

    private void combo2doActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2doActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo2doActionPerformed

    private void combo3roActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo3roActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo3roActionPerformed

    private void combo4toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo4toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo4toActionPerformed

    private void combo5toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo5toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo5toActionPerformed

    private void combo10moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo10moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo10moActionPerformed

    private void combo8voActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo8voActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo8voActionPerformed

    private void combo9noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo9noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo9noActionPerformed

    private void combo6toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo6toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo6toActionPerformed

    private void combo7moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo7moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo7moActionPerformed

    private void buttonVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerifyActionPerformed
        // TODO add your handling code here:
        Bets bets = Bets.getBets();                        
        if(!bets.isValidated()){
            int value = JOptionPane.showConfirmDialog(this, "¿Quiere cerrar las apuestas?", "Verificar", JOptionPane.YES_NO_OPTION);
            if(value == 0){
                bets.validate();                
                //saveFile();
            }
        }else{
            saveFile();
        }
        
        
        
        //buttonVerify.setText("Guardar archivo");                    
        
        /*
        Bets.getBets().getRejected().escribir();
        System.out.println("----------------");
        System.out.println("----------------");
        Bets.getBets().getAccepted().escribir();
        System.out.println("----------------");
        System.out.println("----------------");
        Bets.getBets().getNoVerified().escribir();
        */
    }//GEN-LAST:event_buttonVerifyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(!Bets.getBets().isValidated()){
            String nombre = textName.getText();
            String montoSt = textMonto.getText();                
            if(!nombre.trim().isEmpty() && !montoSt.trim().isEmpty()){
                int monto = 0;
                try{
                    monto = Integer.parseInt(montoSt);
                }catch(Exception ex){
                    monto = -1;
                }
                if(monto <= 0){
                    JOptionPane.showMessageDialog(this, "Verifique el monto");
                }else{
                    int primero = Integer.parseInt(combo1ro.getSelectedItem().toString());
                    int segundo = Integer.parseInt(combo2do.getSelectedItem().toString());
                    int tercero = Integer.parseInt(combo3ro.getSelectedItem().toString());
                    int cuarto = Integer.parseInt(combo4to.getSelectedItem().toString());
                    int quinto = Integer.parseInt(combo5to.getSelectedItem().toString());
                    int sexto = Integer.parseInt(combo6to.getSelectedItem().toString());
                    int septimo = Integer.parseInt(combo7mo.getSelectedItem().toString());
                    int octavo = Integer.parseInt(combo8vo.getSelectedItem().toString());
                    int noveno = Integer.parseInt(combo9no.getSelectedItem().toString());
                    int decimo = Integer.parseInt(combo10mo.getSelectedItem().toString());
                    int positions[] = {primero, segundo, tercero, cuarto, quinto,
                                      sexto, septimo, octavo, noveno, decimo};
                    Bet bet = new Bet(nombre, monto, positions);
                    Bets.getBets().addNoVerified(bet);
                    JOptionPane.showMessageDialog(this, "Apuesta agregada exitosamente");
                }
                textName.setText("");
                textMonto.setText("");                        
                combo1ro.setSelectedIndex(0);                
                combo2do.setSelectedIndex(1);
                combo3ro.setSelectedIndex(2);
                combo4to.setSelectedIndex(3);
                combo5to.setSelectedIndex(4);
                combo6to.setSelectedIndex(5);
                combo7mo.setSelectedIndex(6);
                combo8vo.setSelectedIndex(7);
                combo9no.setSelectedIndex(8);
                combo10mo.setSelectedIndex(9);
                SwingUtilities.updateComponentTreeUI(this);                
            }else{
                JOptionPane.showMessageDialog(this, "Todas los campos son obligatorios");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Apuestas cerradas");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Bets bets = Bets.getBets();
        if(bets.isValidated()){
            JOptionPane.showMessageDialog(this, "Apuestas cerradas");
        }
        else if(FileManagment.open()){
            JOptionPane.showMessageDialog(this, "Cargado con éxito");
            //Bets.getBets().getNoVerified().escribir();
            //System.out.println("------------------");
            //System.out.println("------------------");
        }else{
            JOptionPane.showMessageDialog(this, "Error al cargar el archivo");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVerify;
    private javax.swing.JComboBox<String> combo10mo;
    private javax.swing.JComboBox<String> combo1ro;
    private javax.swing.JComboBox<String> combo2do;
    private javax.swing.JComboBox<String> combo3ro;
    private javax.swing.JComboBox<String> combo4to;
    private javax.swing.JComboBox<String> combo5to;
    private javax.swing.JComboBox<String> combo6to;
    private javax.swing.JComboBox<String> combo7mo;
    private javax.swing.JComboBox<String> combo8vo;
    private javax.swing.JComboBox<String> combo9no;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField textMonto;
    private javax.swing.JTextField textName;
    // End of variables declaration//GEN-END:variables
}
